steps:
  - key: push
    label: ":buildkite: push the package to buildkite packages"
    command: .buildkite/scripts/publish.sh
  - label: ":buildkite: download the package from buildkite packages"
    command: .buildkite/scripts/download.sh
    depends_on: push